name: Test
on: [push]

env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --locked --all-extras

      - name: Test with pytest
        run: |
          uv run pytest
